version: '3'
services:
  web:
    container_name: timetrackerweb
    image: dockerimage/employeetracker1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - datacall
    networks:
      - mylinknet
  datacall:
    container_name: timetrackerdata
    restart: always
    image: alirizasaral/timetracker:1
    ports:
      - "8080:8080"
    networks:
      - mylinknet
networks:
  mylinknet:
